- 🔭 I'm currently working on my own Discord bot
- 🌱 I am currently learning the programming language C #
- 📫 How to reach me on Discord: BattleWolf781 # 3081
- 📚 students in Germany
- ⚡ Interesting facts: also modders for the farming simulator, blender knowledge
